version: '3.8'
services:
  db:
    image: postgres:15
    container_name: wallet-db
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: wallet-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wallet
      DB_USER: wallet
      DB_PASSWORD: wallet
    ports:
      - "8080:8080"

volumes:
  db-data: